---
- name: Clone MoniTHOR-FE-BE repository
  git:
    repo: 'https://github.com/ebenhamu/MoniTHOR-FE-BE.git'
    dest: /home/{{ ansible_user }}/work
    version: main

- name: Update frontend configuration to point to backend
  lineinfile:
    path: /home/{{ ansible_user }}/work/MoniTHOR--Project-FE/config.json
    regexp: '"BE_SERVER": .*'
    line: '"BE_SERVER": "{{ hostvars["monithor-be"].ansible_host }}"'

- name: Build Docker image as sudo (frontend)
  ansible.builtin.command:
    cmd: sudo docker build -t monithor_fe:front .
    chdir: /home/{{ ansible_user }}/work/MoniTHOR--Project-FE

- name: Run Docker frontend container
  community.docker.docker_container:
    name: "frontend_container"
    image: "monithor_fe:front"
    state: started
    published_ports:
      - "8080:8080"
    network_mode: host
    restart_policy: always
