---
- name: Clone MoniTHOR-FE-BE repository
  git:
    repo: 'https://github.com/ebenhamu/MoniTHOR-FE-BE.git'
    dest: /home/{{ ansible_user }}/work
    version: main

- name: Build Docker image as sudo (backend)
  ansible.builtin.command:
    cmd: sudo docker build -t monithor_be:beck .
    chdir: /home/{{ ansible_user }}/work/MoniTHOR--Project-BE

- name: Run Docker backend container
  community.docker.docker_container:
    name: "backend_container"
    image: "monithor_be:beck"
    state: started
    published_ports:
      - "5000:5000"
    network_mode: host
    restart_policy: always
