- name: Update system packages
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: 
      - docker.io
      - docker-compose
    state: present
    
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create jenkins_agent work directory
  file:
    path: /home/{{ ansible_user }}/jenkins_agent
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Install Git
  apt:
    name: git
    state: present

- name: Clone MoniTHOR-infra repository
  git:
    repo: 'https://github.com/ebenhamu/MoniTHOR-infra.git'
    dest: /home/{{ ansible_user }}/jenkins_agent/MoniTHOR-infra
    version: master

- name: Print output to console
  debug:
    msg: "Docker is installed and GitHub repository is cloned successfully"
