---
- name: Configure Docker on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create work directory
      file:
        path: /home/{{ ansible_user }}/work
        state: directory
        owner: 1000
        group: 1000
        mode: "0755"

    - name: Install Git
      apt:
        name: git
        state: present

- name: Configure and run backend Docker container on monithor-be
  hosts: monithor-be
  become: yes
  roles:
    - backend

- name: Configure and run frontend Docker container on monithor-fe
  hosts: monithor-fe
  become: yes
  roles:
    - frontend

- name: Configure and run database Docker container on monithor-db
  hosts: monithor-db
  become: yes
  tasks:
    - name: Create PostgreSQL data directory
      file:
        path: /home/{{ ansible_user }}/postgres_data
        state: directory
        owner: 1000
        group: 1000
        mode: "0755"

    - name: Change ownership of postgres_data directory
      command: sudo chown -R 999:999 /home/{{ ansible_user }}/postgres_data

    - name: Pull PostgreSQL image
      docker_image:
        name: postgres
        tag: "13"
        source: pull

    - name: Run PostgreSQL container
      docker_container:
        name: my_postgres_db
        image: postgres:13
        state: started
        restart_policy: always
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: storedb
        volumes:
          - /home/{{ ansible_user }}/postgres_data:/var/lib/postgresql/data
        ports:
          - "5432:5432"

    - name: Copy init_db.sql to PostgreSQL container
      command: docker cp init_db.sql my_postgres_db:/init_db.sql

    - name: Initialize database with init_db.sql
      command: docker exec my_postgres_db psql -U myuser -d storedb -f /init_db.sql
