apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monithor_backend
spec:
  serviceName: "backend-service"
  replicas: 1
  selector:
    matchLabels:
      app: monithor_backend
  template:
    metadata:
      labels:
        app: monithor_backend
    spec:
      containers:
      - name: monithor_backend
        image: monithor:be
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  clusterIP: None
  selector:
    app: monithor_backend
  ports:
  - port: 5000
    targetPort: 5000
---    
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: monithor
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - protocol: TCP
      port: 5000
  egress:
  - to:
    - protocol: TCP
      port: 8080

