apiVersion: apps/v1
kind: Deployment
metadata:
  name: monithor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monithor-frontend
  template:
    metadata:
      labels:
        app: monithor-frontend
    spec:
      containers:
      - name: monithor-frontend
        image: monithor:fe
        env:
        - name: BACKEND_IP
          value: "backend-service"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: monithor-frontend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: monithor-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: monithor-backend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: monithor-backend
    ports:
    - protocol: TCP
      port: 5000